### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by mathiasverraes** [mathiasverraes/mathiasverraes.github.com#11]
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;

**Comment by mzeinstra** [comment]
This issue can be closed, I've verified that the font-family is indeed "font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;"

**Comment by mathiasverraes** [comment]
Ohai Maarten, thank you for your indispensable contribution! At last, we can lay this issue to rest, gods be thanked!

**Comment by mzeinstra** [comment]
I'm glad to be of help. Finally my many years of training and experience culminated into being able to assist you in this tough issue. 

I guess that I'll have to look for a new life goal now..

**Comment by mathiasverraes** [comment]
I hear cancer hasn't been cured yet.
